id: PFE458055
initial_creation_type: input
source_metadata:
  title: Āśvalāyanagṛhyasūtra
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Veda -- Vedāṅga -- Gṛhyasūtra
  data entry: Muneo Tokunaga
  contribution to GRETIL: Muneo Tokunaga
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:49:32.566924'
last_modified_at: '2022-03-09T14:49:32.566936'
